apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/jaeger-product.openshift-distributed-tracing: ""
  name: jaeger-product
  namespace: openshift-distributed-tracing
spec:
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace

  # OCP 4.12 / 4.13
  #   oc get packagemanifests jaeger -n openshift-marketplace -o json | jq .status.channels[].name
  channel: stable

#  startingCSV: jaeger-operator.v1.47.0-2
