kind: ServiceMeshMember
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: demo-vm-ossm #TODO: change to dynamically created namespace from RHDH
spec:
  controlPlaneRef:
    name: basic
    namespace: istio-system