kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-puller
  namespace: build-dotnet
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo-vm-ossm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
